title: Registry Statuses Vocabulary
email: nicholas.car@surroundaustralia.com
description: >- # this means to ignore newlines until "baseurl:"
  This vocabulary is a re-published and only marginally changed version of the Registry Ontology's (http://epimorphics.com/public/vocabulary/Registry.html) 
  *Status* vocabulary (online in RDF: http://purl.org/linked-data/registry). The only real change to content has been the addition of the term `unstable`. 
  This re-publication has been performed to allow the IRIs of each vocab term (skos:Concept) to resolve to both human-readable and machine-readable forms 
  of content (HTML and RDF), using HTTP content negotiation.

  Note that just like the original form of this vocabulary, while it is a SKOS vocabulary implemented as a single skos:ConceptScheme, it is also an OWL 
  Ontology and that each *Status* is both a skos:Concept and a reg:Status individual.
baseurl: "/reg-statuses" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
